# Generated by Django 4.2.6 on 2023-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
