# Generated by Django 4.2.6 on 2023-10-29 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0005_alter_payments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_of_last_modification',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_of_last_modification',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
